services:
  db:
    image: mysql:8.0
    container_name: community-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: community_db
      MYSQL_USER: community
      MYSQL_PASSWORD: pass1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: community-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/community_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: community
      SPRING_DATASOURCE_PASSWORD: pass1
      # Spring Security 설정 추가
      SPRING_SECURITY_FILTER_ORDER: -100
      SPRING_SECURITY_DEBUG: "true"
      # Servlet 오류 관련 설정
      SERVER_ERROR_INCLUDE_STACKTRACE: "always"
      SERVER_ERROR_WHITELABEL_ENABLED: "true"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "DEBUG"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge